import { PrimeVueResolver } from 'unplugin-vue-components/resolvers';

export interface ConfigOptions {
  dirs?: string[];
  dts?: string;
  primevue?: boolean;
}

function defineConfig(options: ConfigOptions = {}) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const config: Record<string, any> = {
    dts: options.dts ?? './types/autogenerated/components.d.ts',
    dirs: ['./src/components', ...(options.dirs ?? [])],
    extensions: ['vue'],
    deep: true,
    version: 3
  };

  if (options.primevue) {
    config.resolvers = [PrimeVueResolver({ prefix: 'P' })];
  }

  return config;
}

export default defineConfig;
