import type { Plugin } from 'vite';
import RadixVueResolver from 'radix-vue/resolver';
import components from 'unplugin-vue-components/vite';
import { PrimeVueResolver } from 'unplugin-vue-components/resolvers';

export interface ConfigOptions {
  dirs?: string[];
  dts?: string;
  resolvers?: {
    primevue?: boolean;
    radix?: boolean;
  };
}

export default function plugin(options: ConfigOptions = {}): Plugin {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const config: Record<string, any> = {
    dts: options.dts ?? './types/autogenerated/components.d.ts',
    dirs: ['./src/components', ...(options.dirs ?? [])],
    extensions: ['vue'],
    deep: true,
    version: 3
  };

  const resolvers = [];
  if (options.resolvers?.primevue) {
    resolvers.push(PrimeVueResolver({ prefix: 'P' }));
  }

  if (options.resolvers?.radix) {
    resolvers.push(RadixVueResolver({ prefix: 'R' }));
  }

  if (resolvers.length > 0) {
    config.resolvers = resolvers;
  }

  return components(config);
}
